# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
defaults: &defaults
  docker:
    - image: circleci/openjdk:8-jdk
    
version: 2
jobs:
  build:
    <<: *defaults
    steps:
    - checkout
    - run: mvn clean install
    - store_test_results:
        path: target/surefire-reports

  build-jdk9:
    docker:
    - image: circleci/openjdk:9-jdk
    steps:
    - checkout
    - run: mvn clean install

  build-jdk10:
    docker:
    - image: circleci/openjdk:10-jdk
    steps:
    - checkout
    - run: mvn clean install

  build-jdk11:
    docker:
    - image: circleci/openjdk:11-jdk
    steps:
    - checkout
    - run: mvn clean install
            
  deploy:
    <<: *defaults
    steps:
    - checkout
    - run: mvn -s .circleci.settings.xml deploy -Dmaven.test.skip=true

  release:
    <<: *defaults
    steps:
    - checkout
    - run: git config --global user.email "$GITHUB_EMAIL"
    - run: git config --global user.name "$GITHUB_USERNAME"
    - run: mvn -s .circleci.settings.xml -B release:prepare -Dmaven.test.skip=true

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
#      - build-jdk9
#      - build-jdk10
      - build-jdk11
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
