# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
defaults: &defaults
  docker:
  - image: circleci/openjdk:8-jdk

defaults-env: &defaults-env
  environment:
    _JAVA_OPTIONS: -Xms1g -Xmx2g

version: 2
jobs:
  build:
    <<: *defaults
    <<: *defaults-env
    steps:
    - checkout
    - restore_cache:
        keys:
          - m2-cache-v0.1
    - run: make build-ci
    - store_test_results:
        path: target/surefire-reports
    - save_cache:
        key: m2-cache-v0.1
        paths:
          - "$HOME/.m2"

  build-jdk16:
    docker:
    - image: cimg/openjdk:16.0.0
    <<: *defaults-env
    steps:
    - checkout
    - restore_cache:
        keys:
        - m2-cache-v0.1
    - run: make build-ci
    - store_test_results:
        path: target/surefire-reports
    - save_cache:
        key: m2-cache-v0.1
        paths:
        - "$HOME/.m2"

  deploy:
    <<: *defaults
    steps:
    - checkout
    - run: make deploy-ci

  release:
    <<: *defaults
    steps:
    - checkout
    - run: make release-ci

workflows:
  version: 2
  build-deploy:
    jobs:
    - build
    - build-jdk16
    - deploy:
        requires:
        - build
        filters:
          branches:
            only: master
