# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
defaults: &defaults
  docker:
  - image: circleci/openjdk:8-jdk

defaults-env: &defaults-env
  environment:
    _JAVA_OPTIONS: -Xms1g -Xmx2g

version: 2
jobs:
  build:
    <<: *defaults
    <<: *defaults-env
    steps:
    - checkout
    - run: mvn -s .circleci.settings.xml clean install
    - store_test_results:
        path: target/surefire-reports

  build-jdk11:
    docker:
    - image: circleci/openjdk:11-jdk
    <<: *defaults-env
    steps:
    - checkout
    - run: mvn -s .circleci.settings.xml clean install

  deploy:
    <<: *defaults
    steps:
    - checkout
    - run: mvn -s .circleci.settings.xml deploy -DskipTests

  release:
    <<: *defaults
    steps:
    - checkout
    - run: git config --global user.email "$GITHUB_EMAIL"
    - run: git config --global user.name "$GITHUB_USERNAME"
    - run: mvn -s .circleci.settings.xml -B release:prepare -Darguments="-DskipTests"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - build-jdk11
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
